name: documentation

on: [workflow_dispatch]

permissions:
  contents: write
env:
  UV_SYSTEM_PYTHON: 1
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync
      - name: Sphinx build
        run: |
          cd docs/ && uv run sphinx-build source _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/